local Object = require("classes.ControllerPrototype")
local Screen = Object:new("screen", nil, nil)
local Body = Object:new("body", nil, Screen)
--local controller4 = Object:new("cuadradito4", {x = 0, y = 0, width = Body:get("width")/3, height = controller:get("height")/3})
--controller4:set("color", {0.1, 0.4, 0.7})
Body:set("color", 1)
local controller = Object:new("cuadradito1", {x = 0, y = 0, width = Body:get("width"), height = 120})
controller:set("color", 0)
Body:append(controller)
local controller2 = Object:new("cuadradito2", {x = 0, y = 0, width = Body:get("width")/3, height = controller:get("height")/3})
controller2:set("color", 0.4)
controller2:set("margin_bottom", 20)
local controller3 = Object:new("cuadradito3", {x = 0, y = 0, width = Body:get("width")/3, height = controller:get("height")/3})
controller3:set("color", {0.7, 0.4, 0.2})
controller:append(controller2)
controller:append(controller3)
--controller:append(controller4)
controller2:set("margin_right", 30)
controller:remove(1)